name: antibody-design
channels:
  - conda-forge
  - bioconda
dependencies:
  - pandas
  - numpy
  - pytorch
  - lightning
  - matplotlib
  - SciencePlots
  - seaborn
  - bokeh
  - ipykernel
  - ipywidgets
  - jupyter
  - tqdm
  - click
  - biopython
  - gitpython
